---
version: 3.8.3
name: jimnist
description: a site all about me
# url: https://jimnist.com
repository: https://github.com/jimnist/jimnist.com
timezone: America/Los_Angeles
# twitter:
#   username: nachonist
# logo: "/img/logo-2x.png"
# google_analytics_id: UA-50755011-1
# google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY
# plugins:
# - jekyll-avatar
# - jekyll-feed
# - jekyll-mentions
# - jekyll-redirect-from
# - jekyll-seo-tag
# - jekyll-sitemap
# - jemoji
# sass:
#   sass_dir: _sass
#   style: compressed
exclude:
# - CNAME
- README.md
